title: Gabriel Moreno's Page
logo: "/images/Me.jpg?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>An insight to my work in progress project <br>
theme: jekyll-theme-midnight

